//---------------------------------------------------------------------------------------
// Method description...
// 
// Params:
//   arg1: 
//
// Return Params:
//   rarg1: 
//
// Returns: 
//
// Notes:     
// Examples:  
// See:       
//---------------------------------------------------------------------------------------
&blueprint

(Actor hit, String bone_name, Vector3 location)
[
print("hello")
]
  // Replace with custom code body or leave blank for C++ routine.

