//---------------------------------------------------------------------------------------
// Method description...
// 
// Params:
//   arg1: 
//
// Return Params:
//   rarg1: 
//
// Returns: 
//
// Notes:     
// Examples:  
// See:       
//---------------------------------------------------------------------------------------

(Vector3 hit_velocity)
[
@health:= 
  [
    [
      @health>>Real-hit_velocity.length()
    ]
    *GameLib.world_delta_seconds(this)]>>Integer
    
   println(@health>>String)
] 

  // Replace with custom code body or leave blank for C++ routine.

