//---------------------------------------------------------------------------------------
// Method description...
// 
// Params:
//   arg1: 
//
// Return Params:
//   rarg1: 
//
// Returns: 
//
// Notes:     
// Examples:  
// See:       
//---------------------------------------------------------------------------------------
&blueprint
() 
[
  LogLib.log_text(this,@current_velocity>>String,Name!("TestCharacter"))
]
  // Replace with custom code body or leave blank for C++ routine.

